
import type { Course } from './types';
import { BookOpenIcon, BriefcaseIcon, ChartBarIcon, UsersIcon, CurrencyDollarIcon, StarIcon, LightBulbIcon, CodeBracketIcon, ShieldCheckIcon, CubeIcon, BrainIcon, SparklesIcon, ScaleIcon } from './components/icons';

export const COURSES: Course[] = [
  { id: 'karibu-giniaz-college', title: 'Karibu Giniaz College', description: 'Jifunze historia, dira, na maisha ya chuo cha Giniaz.', icon: CubeIcon },
  { id: 'life-skills', title: 'Life Skills', description: 'Jifunze stadi muhimu za maisha.', icon: SparklesIcon },
  { id: 'biashara', title: 'Biashara', description: 'Gundua misingi ya kuanzisha biashara.', icon: BriefcaseIcon },
  { id: 'business-management', title: 'Usimamizi wa Biashara', description: 'Jifunze kuendesha biashara kwa ufanisi.', icon: ChartBarIcon },
  { id: 'project-management', title: 'Usimamizi wa Miradi', description: 'Panga na tekeleza miradi kwa mafanikio.', icon: BookOpenIcon },
  { id: 'people-management', title: 'Usimamizi wa Watu', description: 'Jenga timu imara na yenye tija.', icon: UsersIcon },
  { id: 'financial-management', title: 'Usimamizi wa Fedha', description: 'Dhibiti fedha zako binafsi na za biashara.', icon: CurrencyDollarIcon },
  { id: 'leadership', title: 'Uongozi', description: 'Kuza uwezo wako wa kuongoza.', icon: StarIcon },
  { id: 'injili', title: 'Injili', description: 'Fahamu kwa undani mafundisho ya kiroho.', icon: ScaleIcon },
  { id: 'good-leadership', title: 'Uongozi Bora', description: 'Jifunze siri za kuwa kiongozi bora.', icon: LightBulbIcon },
  { id: 'it', title: 'Information Technology', description: 'Ingia katika ulimwengu wa teknolojia.', icon: CodeBracketIcon },
  { id: 'ethical-hacker', title: 'Ethical Hacker Knowledge', description: 'Jifunze usalama wa mtandao kimaadili.', icon: ShieldCheckIcon },
  { id: 'product-creation', title: 'Uundaji wa Bidhaa', description: 'Kutoka wazo hadi bidhaa sokoni.', icon: CubeIcon },
  { id: 'conscious-mind', title: 'Conscious Mind', description: 'Elewa nguvu ya akili inayotambua.', icon: BrainIcon },
  { id: 'subconscious-mind', title: 'Subconscious Mind', description: 'Gundua siri za akili isiyotambua.', icon: BrainIcon },
  { id: 'best-employee', title: 'Kuwa Mfanyakazi Bora (Mwajiriwa)', description: 'Pata mbinu za kuwa mfanyakazi wa mfano na mwenye tija.', icon: BriefcaseIcon },
  { id: 'wealth-from-salary', title: 'Tengeneza Utajiri Kupitia Mshahara', description: 'Jifunze kuwekeza na kukuza kipato chako ukiwa umeajiriwa.', icon: ChartBarIcon },
  { id: 'be-competent', title: 'Kuwa Hodari Popote Ulipo', description: 'Jenga uwezo na umahiri katika kila eneo la maisha yako.', icon: StarIcon },
  { id: 'control-emotions', title: 'Kudhibiti Mihemko Yako', description: 'Elewa na dhibiti hisia zako kwa mafanikio binafsi na kitaaluma.', icon: BrainIcon },
  { id: 'wisdom-of-the-wise', title: 'Hekima ya Mwenye Hekima', description: 'Jifunze kanuni za Hekima zinazoongoza maisha yenye mafanikio.', icon: LightBulbIcon },
  { id: 'increase-cashflow', title: 'Ongeza Mzunguko Wako wa Fedha', description: 'Gundua njia za kuongeza vyanzo vya mapato na kuboresha mtiririko wa fedha.', icon: CurrencyDollarIcon },
  { id: 'stress-management', title: 'Stress Management', description: 'Jifunze mbinu za kudhibiti na kupunguza msongo wa mawazo.', icon: BrainIcon },
  { id: 'disaster-management', title: 'Disaster Management', description: 'Jifunze jinsi ya kujiandaa na kukabiliana na majanga mbalimbali.', icon: ShieldCheckIcon },
  { id: 'utanashati', title: 'Utanashati', description: 'Jifunze mbinu za kuwa nadhifu na mwenye mvuto.', icon: SparklesIcon },
  { id: 'nidhamu-ya-pesa', title: 'Nidhamu ya Pesa', description: 'Jenga nidhamu katika matumizi na uwekezaji wa fedha.', icon: CurrencyDollarIcon },
  { id: 'nidhamu-binafsi', title: 'Nidhamu Binafsi', description: 'Jenga tabia na nidhamu ya kufikia malengo yako.', icon: StarIcon },
  { id: 'mjue-mkeo', title: 'Mjue Mkeo', description: 'Elewa saikolojia na mahitaji ya mkeo kwa ndoa yenye furaha.', icon: UsersIcon },
  { id: 'kozi-ya-maisha', title: 'Uundaji wa Mifumo', description: 'Angazia maisha kama mifumo, kama vile mfumo wa uchumi, na jifunze mbinu za kuunda mifumo yako mwenyewe.', icon: BookOpenIcon },
  { id: 'furahia-maisha', title: 'Furahia Maisha', description: 'Gundua siri za kuishi maisha ya furaha na utoshelevu.', icon: SparklesIcon },
  { id: 'mjasiriamali-plus', title: 'Mjasiriamali Plus', description: 'Jifunze kutengeneza bidhaa za chakula, vipodozi, na mbinu za biashara.', icon: SparklesIcon },
  { id: 'uongozi-wa-familia', title: 'Uongozi wa Familia', description: 'Jifunze misingi ya uongozi bora kwa wanaume katika kusimamia familia zao kwa hekima na upendo.', icon: UsersIcon },
  { id: 'utoaji-wa-amri', title: 'Utoaji wa Amri', description: 'Elewa sanaa na mbinu za utoaji wa amri katika ngazi ya familia na misingi ya kijeshi.', icon: ShieldCheckIcon },
  { id: 'app-creator-24-tutorial', title: 'App Creator 24 Tutorial', description: 'Jifunze hatua kwa hatua uundaji wa apps za offline na online, kutumia AI, na jinsi ya kupata viungo vya maudhui kupitia App Creator 24.', icon: CodeBracketIcon },
  { id: 'mwanamke-wa-hisia', title: 'Mwanamke wa Hisia', description: 'Uchambuzi wa kina kuanzia kiwango cha atomu kuhusu mwanamke wa hisia kwenye ndoa, familia, uchumi, vipaji, na mafanikio ya maisha.', icon: BrainIcon },
  { id: 'mwanaume-wa-hisia', title: 'Mwanaume wa Hisia', description: 'Uchambuzi makini kuhusu mwanaume wa hisia kwenye familia, kazi, ibada, vipaumbele, na mbinu za kujenga utajiri wa kudumu.', icon: BrainIcon },
  { id: 'sanaa-ya-mwonekano', title: 'Sanaa ya Mwonekano', description: 'Mbinu za kuboresha mwonekano wako, mavazi, na jinsi ya kujitokeza kijamii kwa ujasiri mkubwa.', icon: SparklesIcon },
  { id: 'utunzaji-wa-kumbukumbu', title: 'Utunzaji wa Kumbukumbu', description: 'Jifunze mifumo na mbinu bora za kuhifadhi nyaraka na taarifa muhimu za kimaisha na kibiashara.', icon: BookOpenIcon },
  { id: 'familia-ya-mfano', title: 'Familia ya Mfano', description: 'Misingi ya kujenga na kulea familia yenye misingi imara, upendo, maadili mema na mafanikio yasiyoyumba.', icon: UsersIcon },
  { id: 'uwekezaji', title: 'Uwekezaji', description: 'Mwongozo rahisi wa kuanza kuwekeza fedha zako kwenye fursa salama ili kukuza mtaji wako na kufikia uhuru wa kifedha.', icon: ChartBarIcon },
  { id: 'akili-bandia', title: 'Akili Bandia (AI)', description: 'Ingia kwenye ulimwengu wa AI; jifunze dhana, zana, na mbinu za kutumia akili bandia kurahisisha kazi na maisha yako.', icon: BrainIcon },
  { id: 'social-skills', title: 'Social Skills', description: 'Jenga uwezo wa kujieleza kwa ufasaha, kuwasiliana vyema, na kujenga uhusiano madhubuti na imara na watu mbalimbali.', icon: UsersIcon },
  { id: 'elimu-ya-uchumi-familia', title: 'Elimu ya Uchumi Ngazi ya Familia', description: 'Stadi za kudhibiti bajeti ya familia, kuongeza vyanzo vya mapato, na kufanya uamuzi sahihi wa kifedha katika nyumba.', icon: CurrencyDollarIcon },
  { id: 'mke-wa-hisia', title: 'Mke wa Hisia (Mjue Mkeo)', description: 'Uchambuzi makini kuhusu mke wa hisia kwenye ndoa: saikolojia yake, mihemko yake kuanzia ngazi ya atomu, mbinu za kuishi naye kwa busara na kujaza amani.', icon: BrainIcon },
  { id: 'ufundishaji-mbinu', title: 'Ufundishaji: Mbinu za Ufundishaji', description: 'Jifunze mbinu bora za ufundishaji kwa ajili ya kufikisha ujumbe kwa ufasaha.', icon: BookOpenIcon },
  { id: 'ukweli-mchungu-maisha', title: 'Ukweli mchungu kuhusu maisha', description: 'Uchambuzi wa kina kuhusu familia, uchumi, jamii, imani ya dini, heshima, na mwonekano wako.', icon: LightBulbIcon },
  { id: 'ulinzi-wa-kiroho', title: 'Ulinzi wa Kiroho', description: 'Mbinu za kulinda maisha yako ya kiroho dhidi ya changamoto za kimashetani.', icon: ShieldCheckIcon },
  { id: 'hali-halisi-nyakati', title: 'Hali halisi ya nyakati za sasa', description: 'Uchambuzi wa matukio ya sasa na jinsi ya kuishi kwa busara.', icon: LightBulbIcon },
  { id: 'eskatolojia-hatima', title: 'Kozi ya Eskatolojia', description: 'Masomo 12 yenye mtiririko sahihi kabisa wa kinabii wa wokovu kuanzia uumbaji hadi mwisho katika picha ya historia, maisha ya sasa, na siku zijazo.', icon: BookOpenIcon },
  { id: 'mwalimu-neno-mungu', title: 'Mwalimu wa Neno la Mungu', description: 'Jinsi ya kuwa mwalimu bora wa Neno la Mungu.', icon: BookOpenIcon },
  { id: 'biblia-kiwango-juu', title: 'Jifunze Biblia kwa kiwango cha juu', description: 'Uchambuzi wa kina wa Neno la Mungu.', icon: BookOpenIcon },
  { id: 'kuongoza-ibada', title: 'Jinsi ya kuongoza Ibada', description: 'Mbinu za kuongoza ibada kwa ufanisi.', icon: UsersIcon },
  { id: 'ukweli-sabato', title: 'Ukweli kuhusu Sabato', description: 'Mafundisho kamili kuhusu Sabato.', icon: BookOpenIcon },
  { id: 'soma-biblia-mistari', title: 'kozi ya kusoma biblia na Mistari ya kusimamia unapo oomba', description: 'Jifunze kusimamia mistari ya Biblia unapoomba.', icon: BookOpenIcon },
  { id: 'family-disaster-management', title: 'Family Disaster Management', description: 'Mbinu za kukabiliana na majanga katika ngazi ya familia.', icon: ShieldCheckIcon },
  { id: 'mapenzi-ya-mungu', title: 'Mapenzi ya Mungu', description: 'Jifunze jinsi ya kuomba kulingana na mapenzi ya Mungu na kukuza uchumi kwa kufuata kanuni Zake za ki-Mungu.', icon: ScaleIcon },
  { id: 'tuombeje-mapenzi-ya-mungu', title: 'Tuombeje kulingana na Mapenzi ya Mungu?', description: 'Mbinu za kuomba kwa usahihi na kupokea majibu kulingana na mapenzi ya dhati ya Mungu.', icon: BookOpenIcon },
  { id: 'kanuni-mungu-uchumi', title: 'Kanuni za Mungu zinazoongoza Uchumi', description: 'Uchambuzi wa sheria na kanuni zote za ki-Mungu zinazosimamia uchumi na mafanikio ya kifedha.', icon: CurrencyDollarIcon },
  { id: 'kukuza-uchumi-ki-mungu', title: 'Je, tunawezaje kukuza uchumi kulingana na kanuni za Ki-Mungu?', description: 'Hatua za vitendo za kukuza vipato vyetu na kuwekeza kwa mafanikio tukiongozwa na kanuni za ki-Mungu.', icon: ChartBarIcon },
  { id: 'kwanini-waumini-wanafeli-uchumi', title: 'Kwanini waumini wengi wanafeli kiuchumi?', description: 'Uchunguzi wa kina wa sababu za kiroho, kifikra, na kiutendaji zinazowafanya waumini washindwe kifedha.', icon: LightBulbIcon },
  { id: 'kuvuta-uwepo-wa-mungu', title: 'Jinsi ya kuvuta/kuvutia uwepo wa Mungu', description: 'Jifunze mbinu na kanuni thabiti za ki-Mungu za kuvuta, kudumisha na kuishi katika uwepo Wake wa kudumu.', icon: SparklesIcon },
  { id: 'prompts-engineering', title: 'Prompt Engineering', description: 'Jifunze sanaa na sayansi ya kuandika maelekezo thabiti (prompts) ili kupata majibu bora na sahihi kutoka kwa mifumo ya Akili Bandia (AI).', icon: CodeBracketIcon },
  { id: 'tendo-la-ndoa-tamu', title: 'Tendo la Ndoa Tamu (Jinsi ya Kumuandaa Mkeo)', description: 'Jifunze siri na mbinu sahihi za kumuandaa mkeo kihisia, kisaikolojia, na kimwili kwa ajili ya ndoa yenye furaha na kuridhika kwa asili.', icon: UsersIcon },
  { id: 'kumfanya-mwanamke-akupende', title: 'Mbinu za Kumfanya Mwanamke Akupende, Akuwaze na Akumis', description: 'Jifunze jinsi ya kujenga mvuto usiofutika na kushikilia moyo wa mwanamke ili akupende, akuheshimu, na akuhitaji maishani mwake wakati wote.', icon: BrainIcon },
  { id: 'mtaji-laki-tano-kibaha', title: 'Mtaji wa Laki Tano Kibaha (Kutengeneza Utajiri na Fursa)', description: 'Jifunze jinsi ya kuanza biashara na kutengeneza utajiri kwa mtaji wa laki tano (500,000 TZS) mkoani Kibaha, zikiwemo aina za fursa na mbinu za kutoboa.', icon: CurrencyDollarIcon },
  { id: 'api-economy', title: 'API Economy', description: 'Jifunze kuhusu aina za Google API Keys, kusanifu programu zisizo na kodi (No-code apps), kuziunganisha na mifumo ya malipo, na kupata kipato thabiti.', icon: CodeBracketIcon },
  { id: 'mindfulness-of-god', title: 'Mindfulness of God', description: 'Jifunze kuwa na utambuzi wa kina, umakini wa kiroho na kuishi katika uwepo wa Mungu kila wakati katika kila eneo la maisha na fikra zako.', icon: BrainIcon },
  { id: 'mkristo-viwango-vya-kinabii', title: 'Mkristo wa Viwango vya Kinabii', description: 'Jinsi ya kufikia viwango vya kutamka neno likawa, kuona mambo kiroho, na kuombea wagonjwa na kuponya kwa kutumia mamlaka ya Neno la Mungu na mistari ya Biblia.', icon: SparklesIcon },
  { id: 'kufunga-na-kufungua-kiroho', title: 'Jinsi ya kufunga na kufungua jambo lolote kiroho na matokeo yake', description: 'Mamlaka ya funguo za ufalme wa mbinguni, kanuni za kufunga na kufungua katika ulimwengu wa roho, na matokeo yake dhahiri kulingana na Mathayo 16:19 na 18:18.', icon: ShieldCheckIcon },
  { id: 'ibada-ya-kikristo', title: 'Kozi ya Ibada ya kikristo', description: 'Misingi ya kina ya ibada ya kweli katika Roho na Kweli, kuabudu na kusifu, madhabahu ya moyo, na jinsi ya kumvutia Mungu kulingana na Yohana 4:23-24.', icon: BookOpenIcon },
  { id: 'kusafisha-nyota-kiroho', title: 'Kozi ya Namna ya Kusafisha nyota yako kiroho', description: 'Mafundisho ya kina ya ki-Biblia kuhusu nyota na hatima ya mwanadamu, kuondoa giza na vifungo vya adui, na kuifanya nyota yako ing\'ae kwa utukufu wa Mungu kulingana na Isaya 60:1-3 na Mathayo 2:1-2.', icon: StarIcon },
];
